export const config = {
  buttons: {
    btnSearchText: "Let’s start ",
    btnModalLogInText: "Log in ",
    btnModalSignUpText: "Sign up ",
    btnReturnText: "Return ",
    btnCheckStatusText: "Check status ",
    btnShowText: "Show more ",
    btnOrderText: "Order ",
    btnSaveText: "Save ",
    btnLogOutText: "Log out ",
  },
  links: {
    navLinkAboutText: "About us",
    navLinkPrivacyText: "Privacy&Security",
    navLinkContactText: "Contact us",
    navLinkHelpText: "Help center",
    navLinkFaqsText: "FAQs",
    navLinkProfileText: "Edit profile",
    navLinkOrdersText: "My orders",
    navLinkBooksText: "All books",
    navLinkYourOrdersText: "Your orders",
    navLinkSettingsText: "Settings",
  },
  inputs: {
    placeholderText: "Search by author, title, name",
    labelInputUserText: "Username",
    labeInputBirthDateText: "Your birthdate",
    labelInputEmailText: "Email ",
    labelInputPasswordText: "Password ",
    labelInputNewPasswordText: "New password ",
  },
  heading: {
    startTitleText: " BIld your library",
    commentLibraryText:
      "Over 400.000 books from fiction to the business literature",
    modalInvitationText: "Welcome to Fox Library",
    modalRequestText: "Log In to Fox Library",
    descriptionBookText: "About book",
    connectionText: "Stay connected",
    titlePageText: "Settings",
    blockWaitText: "Waiting for",
    listBookText: "List of your books",
    descriptionLibraryText: "About Fox Library",
    listHelpText: "Help",
    accountText: "My account",
    titleBlockWaitBookText: "Oops! You are not waiting for any book ",
    titleBlocListBookText: "Oops! You haven't added any book yet ",
  },
};
